steps:
  - name: 'my-training-repo'
    args: ['build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/my-training-repo/node-server1', '.']

  - name: 'my-training-repo/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/my-training-repo/node-server1']

  - name: 'my-training-repo-gcloudsdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - node-server1
      - --image=europe-docker.pkg.dev/$PROJECT_ID/my-training-repo/node-server1
      - --platform=managed
      - --region=europe-west1
      - --allow-unauthenticated

images:
  - europe-docker.pkg.dev/$PROJECT_ID/my-training-repo/node-server1

options:
  logging: CLOUD_LOGGING_ONLY
