steps:
  - name: 'my-training-repo/cloud-builders/docker'
    args: ['build', '-t', 'my-training-repo/$PROJECT_ID/node-server1', '.']

  - name: 'my-training-repo/cloud-builders/docker'
    args: ['push', 'my-training-repo/$PROJECT_ID/node-server1']

  - name: 'my-training-repo/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - node-server1
      - --image=my-training-repo/$PROJECT_ID/node-server1
      - --platform=managed
      - --region=europe-west1
      - --allow-unauthenticated

images:
  - my-training-repo/$PROJECT_ID/node-server1

options:
  logging: CLOUD_LOGGING_ONLY
